site_name: ItsMichael's Lab
site_description: ML, MLOps, and Mental Models
site_author: Mikaeil
site_url: https://itsmikaeil.github.io/

# تنظیمات تم متریال
theme:
  name: material
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    # حالت روشن (با رنگ پس‌زمینه تمیز و پیش‌فرض)
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: red
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # حالت تاریک
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: red
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.sections    # بخش‌بندی و گروه‌بندی منوها
    - navigation.expand      # باز بودن پیش‌فرض زیرشاخه‌ها برای حس کتابی
    - navigation.indexes     # قابلیت کلیک روی سربرگ بخش‌ها
    - toc.follow             # حرکت فهرست سمت راست همگام با اسکرول صفحه
    - navigation.top         # دکمه اسکرول به بالا
    - search.suggest         # پیشنهاد عبارات در جستجو
    - content.code.copy      # دکمه کپی کدها

# اکستنشن‌های مهم برای فرمول ریاضی و کد زدن
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition               # برای باکس‌های "نکته" و "هشدار"
  - pymdownx.details

# ساختار منوی سایت (حتماً مطمئن شو این فایل‌ها در پوشه docs ساخته شده‌اند)
nav:
  - Home: index.md
  - Machine Learning: 
      - Overview: ml/intro.md
      - Deep Learning: ml/dl_notes.md
  - Mental Models: mental_models.md
  - Mathematics: Mathematic Note.md
  - Part I. Background:
      - 1. Why do we learn statistics?: background/intro.md
      - 2. A brief introduction: background/design.md
  - Part II. An Introduction to Python:
      - 3. Getting Started: python/start.md
      - 4. More Concepts: python/concepts.md

# اسکریپت‌های لازم برای اجرای فرمول‌های ریاضی (MathJax امن بدون Polyfill)
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

