site_name: Michael Notes

theme:
  name: material
  language: en
  palette:
    - scheme: default
      primary: blue
      accent: indigo
    - scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Light mode

nav:
  - Home: index.md
  - Python: python.md
  - Statistics: statistics.md
  - AI Engineering: ai.md
  - Machine Learning: ML.md
  - Books: books.md

markdown_extensions:
  - admonition
  - tables
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.highlight