site_name: ItsMichael's Lab
site_description: ML, MLOps, and Mental Models
site_author: Mikaeil
site_url: https://itsmikaeil.github.io/

# تنظیمات تم متریال
theme:
  name: material
  language: en  # اگر می‌خواهی منوها راست‌چین شود روی fa بگذار
  font:
    text: Roboto
    
  palette:
    # حالت روشن
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # حالت تاریک
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs # منوی بالای صفحه
    - navigation.sections # بخش‌بندی منو
    - search.suggest # پیشنهاد در جستجو
    - content.code.copy # دکمه کپی کدها

# اکستنشن‌های مهم برای فرمول ریاضی و کد زدن
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition # برای باکس‌های "نکته" و "هشدار"
  - pymdownx.details

# ساختار منوی سایت (هر فایل جدیدی ساختی اینجا اضافه کن)
nav:
  - Home: index.md
  - Machine Learning: 
      - Overview: ml/intro.md
  - Deep Learning: ml/dl_notes.md
  - Mathematice: Mathematic Note.md
  - Statistics: Statistics.md
  - Linear Algebra: Linear Algebra.md
  - Calculus: Calculus.md
  - Probability: Probability.md
  - Business: Business.md
  - Mental Models: mental_models.md

# تنظیمات ریاضی (MathJax)
